services:
  app:
    build: .
    ports:
      - 8001:8001
      - 8002:5678
    volumes:
      - .:/code
    command: uvicorn src.main:app --host 0.0.0.0 --port 8001 --reload
    restart: always
    depends_on:
      - ollama
      - ollama-webui
    networks:
      - homelab_net

  ollama:
    image: docker.io/ollama/ollama:latest
    ports:
      - 8003:11434
    volumes:
      - .:/code
      - ./ollama/ollama:/root/.ollama
    container_name: ollama
    pull_policy: always
    tty: true
    restart: always
    environment:
      - OLLAMA_KEEP_ALIVE=24h
      - OLLAMA_HOST=0.0.0.0
    networks:
      - homelab_net

  ollama-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: ollama-webui
    volumes:
      - ./ollama/ollama-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - 8004:8080
    environment: # https://docs.openwebui.com/getting-started/env-configuration#default_models
      - OLLAMA_BASE_URLS=http://host.docker.internal:8003
      - WEBUI_URL=http://host.docker.internal:8004
      - DEFAULT_MODELS=llama3.1,mistral
      - ENV=dev
      - WEBUI_AUTH=False
      - WEBUI_NAME=valiantlynx AI
      - WEBUI_SECRET_KEY=t0p-s3cr3t
      - NO_PROXY=host.docker.internal 
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped
    networks:
      - homelab_net

networks:
  homelab_net:
    external: false
  
